### PR TITLE
fix: return type issue for php8.1

### PR DESCRIPTION
**Pull request by phpsa**
See Issue: https://github.com/ClickSend/clicksend-php/issues/26

adds `[\ReturnTypeWillChange]` attribute as needed

### CODE REVIEW

**Comment by BafS** [comment]
@mriecken any chance we can merge this? It's waiting since a while

**Comment by BafS** [comment]
@Jaxom-ClickSend @pauldclicksend @mriecken would it be possible to have a look please? It would be great to maintain the official library

**Comment by michaelbutler** [comment]
@BafS Unfortunately, most of this repository is autogenerated code so we can't just manually change the code. If you look at the file headers it is autogenerated by swagger. Also unfortunately, swagger needs to update their code to support this too! Someone opened an issue here:

https://github.com/swagger-api/swagger-codegen/issues/11820

I would recommend opening a PR there, once swagger is updated to support it, ClickSend can re-run the latest swagger to auto-generate with full PHP 8 support.

**Comment by BafS** [comment]
Thank you for your message @mriecken

**Comment by BafS** [comment]
@mriecken could we update the repo with the last generated files?

**Comment by BafS** [comment]
Any news? This PR is open since almost a year now and the fix was merged upstream

**Comment by BafS** [comment]
@mriecken ?

**Comment by davidcumberland** [comment]
How's this branch going? Just signed up and started testing, got spammed with deprecation notices.

**Comment by BafS** [comment]
The repo is pretty much unmaintained, there is no answer from the company since months. We are using this fork: https://github.com/phpsa/clicksend-php

**Comment by michaelbutler** [comment]
Thanks @BafS  .  Or you could just use the REST API directly using your own simple class using CURL.

**Comment by BafS** [comment]
Looks like it's finally fixed with this commit: https://github.com/ClickSend/clicksend-php/commit/dfd555424da4c7d5cfc4dd8b812957c7ee6becc4

**Comment by phpsa** [comment]
Closing this now as tagged v5 available @5.0.79

**Pull request closed without merging**
